#!/usr/bin/env bash
set -e

# Add Gentoo overlay to repos.conf/ and sync it
# Example usage: add_overlay musl https://anongit.gentoo.org/git/proj/musl.git
#
# Arguments:
#
# 1: repo_id - reference used in repos.conf
# 2: repo_url
# 3: repo_mode - optional, default: git
# 4: repo_priority - optional, default: 50

repo_id="$1"
repo_url="$2"
repo_mode="${3:-git}"
repo_priority="${4:-50}"
repo_path='/var/db/repos'

[ ! -d "${repo_path}" ] && mkdir -p "${repo_path}"

tee /etc/portage/repos.conf/"${repo_id}".conf >/dev/null <<END
[${repo_id}]
priority = ${repo_priority}
location = ${repo_path}/${repo_id}
sync-type = ${repo_mode}
sync-uri = ${repo_url}
END

emaint sync -r "${repo_id}"
