#!/usr/bin/env bash
set -e

function die()
{
    echo "::error::$1"
    echo "------------------------------------------------------------------------------------------------------------------------"
    exit 1
}

cat << END
------------------------------------------------------------------------------------------------------------------------
                                 _                    _            _                                    
                                | |                  | |          | |                                   
                 __ _  ___ _ __ | |_ ___   ___ ______| |_ ___  ___| |_ _ __ _   _ _ __  _ __   ___ _ __ 
                / _\` |/ _ \ '_ \| __/ _ \ / _ \______| __/ _ \/ __| __| '__| | | | '_ \| '_ \ / _ \ '__|
               | (_| |  __/ | | | || (_) | (_) |     | ||  __/\__ \ |_| |  | |_| | | | | | | |  __/ |   
                \__, |\___|_| |_|\__\___/ \___/       \__\___||___/\__|_|   \__,_|_| |_|_| |_|\___|_|   
                 __/ |                                                                                  
                |___/
 
               https://github.com/hacking-gentoo/gentoo                             (c) 2019 Max Hacking 
------------------------------------------------------------------------------------------------------------------------
END

# Check for a GITHUB_WORKSPACE env variable
[[ -z "${GITHUB_WORKSPACE}" ]] && die "Must set GITHUB_WORKSPACE in env"
cd "${GITHUB_WORKSPACE}" || exit 2

# Check for an entrypoint.sh file
[[ -x /entrypoint.sh ]] || die "No /entrypoint.sh file!"

# If we are using a binary package cache
if [[ -d "${GITHUB_WORKSPACE}/binpkgs" ]]; then
	rm -rf /var/cache/binpkgs
	ln -s "${GITHUB_WORKSPACE}/binpkgs" /var/cache/binpkgs
	cp /etc/portage/make.binpkg /etc/portage/make.conf/02-hacking-binpkg
	echo "Enabled binary package cache"
fi

# If we are using a distfiles cache
if [[ -d "${GITHUB_WORKSPACE}/distfiles" ]]; then
	rm -rf /var/cache/distfiles
	ln -s "${GITHUB_WORKSPACE}/distfiles" /var/cache/distfiles
	echo "Enabled distfiles cache"
fi

# Execute the entry point
exec /entrypoint.sh
